# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create Release to GitHub"
  lane :create_github_release do |options|
    api_token = options.fetch(:api_token)
    tag_name = options.fetch(:tag_name)

    github_release = set_github_release(
      repository_name: "yutailang0119/sandbox-fastlane",
      api_token: api_token,
      name: tag_name,
      tag_name: tag_name,
      description: "Description by fastalane\n=====",
      is_draft: true,
      is_generate_release_notes: true
    )
  end
end
